# Generated by Django 3.1.4 on 2021-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauren_coworker_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkerstatement',
            name='statement',
            field=models.TextField(max_length=65535),
        ),
    ]
