# Generated by Django 4.0.3 on 2022-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsefacts', '0002_auto_20211118_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsefact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
